### PR TITLE
[New] Display alternate symbols at different scales

### PR DESCRIPTION
**Pull request by CalebRas**
## Description

This PR implements `Display alternate symbols at different scales` in `SAMPLE_CATEGORY` category.
URL to README: [Display alternate symbols at different scales](https://github.com/Esri/arcgis-maps-sdk-swift-samples/tree/Caleb/New-DisplayAlternateSymbolsAtDifferentScales/Shared/Samples/Display%20alternate%20symbols%20at%20different%20scales)

## Linked Issue(s)

- `swift/issues/6187`

## How To Test

- Zoom in and out to see the alternate symbols at different scales.

## Screenshots

display-alternate-symbols-at-different-scales

### CODE REVIEW

**Review by pgruenler — CHANGES_REQUESTED** [review]
One documentation comment looks incomplete.

**Review by pgruenler — APPROVED** [review]

**Review by njarecha — DISMISSED** [review]
Looks good

**Comment by CalebRas** [comment]
Sorry I had to merged with v.next.

**Review by njarecha — APPROVED** [review]

**Review by pgruenler — APPROVED** [review]

**Comment by CalebRas** [comment]
Thank you!

**Pull request merged**
