### PR TITLE
[Fix] Spelling and indentation

### PR DESCRIPTION
**Pull request by CalebRas**
## Description

This PR fix some spelling and indentation issues across the Sample Viewer.

## How To Test

- Ensure the project builds.

### CODE REVIEW

**Review by des12437 — APPROVED** [review]
Looks good.

Can you address the indentation linter warnings in `FilterByDefinitionExpressionOrDisplayFilterView.swift`: 
`Switch and Case Statement Alignment Violation: Case statements should vertically align with their enclosing switch statement` either in this PR or another PR? See the [documentation](https://realm.github.io/SwiftLint/switch_case_alignment.html) for reference.

Screenshot

**Comment by CalebRas** [comment]
> Can you address the indentation linter warnings in `FilterByDefinitionExpressionOrDisplayFilterView.swift`: `Switch and Case Statement Alignment Violation: Case statements should vertically align with their enclosing switch statement` either in this PR or another PR? See the [documentation](https://realm.github.io/SwiftLint/switch_case_alignment.html) for reference.

@des12437  I am not see this warning and it looks like from the screenshot that the cases are already aligned. Do you know what version of swiftlint you are running?

**Comment by des12437** [comment]
> @des12437 I am not see this warning and it looks like from the screenshot that the cases are already aligned. Do you know what version of swiftlint you are running?

I updated my swift lint version and the warnings are resolved.

**Review by rolson — APPROVED** [review]

**Comment by CalebRas** [comment]
Thank you!

**Pull request merged**
