### PR TITLE
[Update] Optimize Mac Catalyst Interface for Mac

### PR DESCRIPTION
**Pull request by philium**
This changes the selected Mac Catalyst Interface to Optimize for Mac:

image

It replaces many non-native (iOS) UI elements with native (macOS) ones, making it look and feel more at home on the platform:

Before | After
--- | ---
Screenshot 2023-04-05 at 8 04 38 AM | Screenshot 2023-04-05 at 8 06 43 AM

### CODE REVIEW

**Review by yo1995 — APPROVED** [review]

**Review by dfeinzimer — APPROVED** [review]

**Comment by yo1995** [comment]
@dfeinzimer After making this change, the basemap gallery looks off. Not sure if it is an issue with SwiftUI/Mac Catalyst itself or sth we can fix. 🤔

**Review by dfeinzimer — CHANGES_REQUESTED** [review]
Sorry, I  jumped the gun on an approval. As Ting pointed out, I think we need to work out some UI bugs before merging this if we officially support macOS.

Screenshot 2023-04-05 at 10 09 20

**Comment by philium** [comment]
Thanks @yo1995 and @dfeinzimer! I should have created this as a draft.

**Comment by yo1995** [comment]
Yes, we can address the issues in this release.

**Review by yo1995 — COMMENTED** [review]
Sample UI that needs to be fixed:

- [ ] Change map view background: sometimes the sliders show, sometimes they don't; same for color picker button.
image
- [ ] Set basemap: basemap gallery button style
- [ ] Show viewshed from point in scene: all the controls
- [ ] Many samples don't show the top bar info button, such as Set min and max extent, Set viewpoint rotation

**Review by yo1995 — APPROVED** [review]
We can apply this change for now so when the new samples come in, we can ensure they are future-proof. Issues can be gradually fixed.

**Review by dfeinzimer — APPROVED** [review]
@philium Should we do the same for the toolkit's equivalent ([#292](https://github.com/Esri/arcgis-maps-sdk-swift-toolkit/pull/292)) as well, since it's a dependency?

**Comment by philium** [comment]
@dfeinzimer Sure!

**Pull request merged**
