### PR TITLE
[Update] 200.1.0 ArcGIS Bundle ID

### PR DESCRIPTION
**Pull request by zkline101**
## Description

This PR updates the ArcGIS Bundle ID which prevents a crash when clicking on the about button.

### CODE REVIEW

**Review by yo1995 — APPROVED** [review]

**Review by saratchandrakarumuri — COMMENTED** [review]
App is still crashing for me when I open the info pane

2023-03-23 at 5 47 PM

**Comment by yo1995** [comment]
Sorry Sarat I should mention, this need to be tested with the local toolkit folder and ArcGIS daily build binary, because…

- 200.0.0-beta doesn't have the same bundle ID
- The source file uses a different bundle ID ("ArcGIS" instead of "com.esri.ArcGIS", for some reason). Only the binary is using the "com.esri.ArcGIS" bundle ID.

**Comment by saratchandrakarumuri** [comment]
@yo1995 Ahhh... Makes sense... I tried with the source code swift package... I will try with daily build now

**Review by saratchandrakarumuri — APPROVED** [review]
Changes looking good

**Comment by zkline101** [comment]
Thank you both

**Pull request merged**
