### PR TITLE
[Update] Swift Lint opt-in rules

### PR DESCRIPTION
**Pull request by CalebRas**
## Description

This PR updates the Swift Lint `opt_in_rules`:

- Removes some that are now [default rules](https://realm.github.io/SwiftLint/rule-directory.html).
- Adds some that are present in the Swift API but were missing here.

## How To Test

Ensure the project builds without warnings.

### CODE REVIEW

**Comment by CalebRas** [comment]
Remove Nimesh since he is out.

**Comment by CalebRas** [comment]
@dfeinzimer Would you like me to make these changes in the toolkit as well?

**Review by dfeinzimer — APPROVED** [review]
> @dfeinzimer Would you like me to make these changes in the toolkit as well?

That would be great!

**Review by des12437 — APPROVED** [review]
Looks good.

**Comment by CalebRas** [comment]
Thank you!

**Pull request merged**
